AppStore/Controllers/UserAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppStore.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;

namespace AppStore.Controllers
{
    public class UserAccountController : Controller
    {
        // GET: UserAccount

        private DbContextModels db =new DbContextModels();
      

        public ActionResult Index()
        {
            using (DbContextModels db=new DbContextModels())
            {
                return View(db.UserRegInfoModels.ToString());
            }
        }

        public ActionResult Reg()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Reg(UserRegInfoModel acco )
        {
            if (ModelState.IsValid)
            {
                using (DbContextModels db =new DbContextModels())
                {
                    db.UserRegInfoModels.Add(acco);
                    db.SaveChanges();
                }
                ModelState.Clear();
                ViewBag.Message = acco.uFirstName + " " + acco.uLastName + " Successfully Registered";
            }
            return View();
        }

        //login
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Login(UserRegInfoModel user )
        {
            using (DbContextModels db = new DbContextModels())
            {
                var usr = db.UserRegInfoModels.Where(u =>u.UserName == user.UserName && u.uPassword == user.uPassword).FirstOrDefault();
                if (usr != null)
                {
                    Session["UserId"] = usr.UserId.ToString();
                    Session["UserName"] = usr.UserName.ToString();
                    return RedirectToAction("Loggined");
                }
                else
                {
                    ModelState.AddModelError("","User Name or Password is wrong");
                }
            }
            return View();
        }

        public ActionResult Loggined()
        {
            if (Session["UserId"] !=null)
            {
                return View();
            }
            else
            {
               return RedirectToAction("Login");
            }
        }

        [HttpGet]
        public ActionResult AdminLogin()
        {
            return View();
        }

        [HttpPost ]
        public ActionResult AdminLogin(AdminModels admin)
        {
            

            var log = db.AdminModelses.Where(u => u.UserName == admin.UserName && u.Password == admin.Password)
                .FirstOrDefault();
            
                if (log !=null)
                {
                    Session["AdminId"] = log.Id.ToString();
                    Session["AdminName"] = log.UserName.ToString();
                    return RedirectToAction("AdminHome");
                }
                else
                {
                        ModelState.AddModelError("", "User Name or Password is wrong");
                }

            return View();
        }


        //[HttpPost]
        public ActionResult AdminHome()
        {
            if (Session["AdminId"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("AdminLogin");
            }
            
        }


       
       
        

        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Login");
        }

    }
}

AppStore/Views/UserAccount/AdminHome.cshtml
@{
    ViewBag.Title = "AdminHome";
    Layout = "~/Views/Shared/_AdminLayoutPage.cshtml";
}
@if (Session["AdminId"] != null)
{
    <h2>AdminHome @Session["AdminName"].ToString()</h2>
   

}

AppStore/Views/UserAccount/AdminLogin.cshtml
@model AppStore.Models.AdminModels

@{
    ViewBag.Title = "AdminLogin";
    Layout = "~/Views/Shared/_LoginRegLayoutPage.cshtml";
}

<h2>AdminLogin</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AdminModels</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AppStore/Views/UserAccount/Index.cshtml
@model IEnumerable<AppStore.Models.UserRegInfoModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LoginRegLayoutPage.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UFirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ULastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UEmail)
        </th>
        
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UFirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ULastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UEmail)
        </td>
        
    </tr>
}

</table>

AppStore/Views/UserAccount/Loggined.cshtml
@{
    ViewBag.Title = "Loggined";
    Layout = "~/Views/Shared/_LoginRegLayoutPage.cshtml";
}

<h2>Loggined</h2>
@if (Session["UserId"] != null)
{
    <h3>hello @Session["UserName"].ToString() </h3>
}

AppStore/Views/UserAccount/Login.cshtml
@model AppStore.Models.UserRegInfoModel

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_LoginRegLayoutPage.cshtml";
}

<h2>Login</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            @Html.LabelFor(model => model.uPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.uPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.uPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    
    @Html.ActionLink("Admin Login", "AdminLogin", "UserAccount")
    @Html.ActionLink("Teacher Login", "TeacherLogin", "Teacher")
    @Html.ActionLink("Student Login", "Login", "Student")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AppStore/Views/UserAccount/Reg.cshtml
@using AppStore.Models;
@model AppStore.Models.UserRegInfoModel

@{
    ViewBag.Title = "Reg";
    Layout = "~/Views/Shared/_LoginRegLayoutPage.cshtml";
}

<h2>Registation</h2>


@using (Html.BeginForm("Reg", "UserAccount", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @if (ViewBag.Message !=null)
        {
            <div class="form-group">
                <div class="col-md-10">@ViewBag.Message</div>
            </div>
        }

        <div class="form-group">
            @Html.LabelFor(model => model.uFirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.uFirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.uFirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.uLastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.uLastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.uLastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.uEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.uEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.uEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.uPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.uPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.uPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.uPhoto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.uPhoto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.uPhoto, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Registation" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Login", "Login", "UserAccount")
    @Html.ActionLink("Teacher Registration  ", "TeacherReg", "Teacher")
    @Html.ActionLink("Student Registration  ", "Registation", "Student")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}